<?php /** @var \App\KpiInterface $this */ ?>
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    <title>KPI</title>
</head>
<body class="bg-dark">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-white">My time is ...</h1>
        </div>
        <div class="col-md-12">
            <form method="GET">
                <div class="form-row align-items-center">
                    <div class="col-auto">
                        <label class="sr-only" for="hours">Hours</label>
                        <div class="input-group mb-2">
                            <input type="number" name="hours"
                                   class="form-control"
                                   value="<?= $this->getHours() ?>" min="0"
                                   id="hours" placeholder="Hours">
                            <div class="input-group-append">
                                <div class="input-group-text">h</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <label class="sr-only" for="minutes">Minutes</label>
                        <div class="input-group mb-2">
                            <input type="number" name="minutes"
                                   class="form-control" id="minutes"
                                   value="<?= $this->getMinutes() ?>" min="0"
                                   placeholder="Minutes">
                            <div class="input-group-append">
                                <div class="input-group-text">m</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <label class="sr-only" for="percent">Percent</label>
                        <div class="input-group mb-2">
                            <input type="number" name="percent"
                                   class="form-control" id="percent"
                                   value="<?= $this->getPercent() ?>"
                                   min="0" max="100"
                                   placeholder="Percent">
                            <div class="input-group-append">
                                <div class="input-group-text">%</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-secondary mb-2">
                            Calculate
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <?php if ($this->isResult()): ?>
            <div class="col-md-12">
                <h2 class="text-white">Result:</h2>
            </div>
            <div class="col-md-12">
                <table class="table table-dark">
                    <thead>
                    <tr>
                        <th scope="col">&nbsp;</th>
                        <th scope="col">Hours</th>
                        <th scope="col">Minutes</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">Min</th>
                        <td><?= $this->getMinTime()->getHours() ?>h</td>
                        <td><?= $this->getMinTime()->getMinutes() ?>m</td>
                    </tr>
                    <tr>
                        <th scope="row">Current</th>
                        <td><?= $this->getHours() ?>h</td>
                        <td><?= $this->getMinutes() ?>m</td>
                    </tr>
                    <tr>
                        <th scope="row">Max</th>
                        <td><?= $this->getMaxTime()->getHours() ?>h</td>
                        <td><?= $this->getMaxTime()->getMinutes() ?>m</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
    </div>
</body>
</html>